### ISSUE TITLE
MissingChannelError - GetVideoPlayInfo

### ISSUE THREAD

**Issue by mr-xiangxu** [aliyun/openapi-core-nodejs-sdk#95]
版本："@alicloud/pop-core": "^1.7.12",
问题描述：
  GetVideoPlayAuth没问题，返回正确结果。
  GetVideoPlayInfo，SDK抛出异常，异常结果如下：

```
{
  "stack": "MissingChannelError: Channel is mandatory for this action., URL: http://vod.cn-shanghai.aliyuncs.com/?AccessKeyId=LTAI5t8***************&Action=GetVideoPlayInfo&Format=JSON&SignatureMethod=HMAC-SHA1&SignatureNonce=04c47f8fd9*********&SignatureVersion=1.0&Timestamp=2022-09-19T12%3A06%3A41Z&Version=2017-03-21&VideoId=bca6bd1d1b83454f840cfb7fa1de5ca6&Signature=Lv4cpbyBH7TqSf*********%3D\n    at /Users/xx/projects/itu/apps/api-server/node_modules/@alicloud/pop-core/lib/rpc.js:213:19\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at Object.getVideoPlayInfo (/Users/xx/projects/itu/apps/api-server/src/external-services/vod/vodClient.ts:52:23)\n    at /Users/xx/projects/itu/apps/api-server/src/backend-api/vod/vodController.ts:45:52",
  "message": "Channel is mandatory for this action., URL: http://vod.cn-shanghai.aliyuncs.com/?AccessKeyId=LTAI5t8QWMW*********&Action=GetVideoPlayInfo&Format=JSON&SignatureMethod=HMAC-SHA1&SignatureNonce=04c47f8fd9f62f10*********&SignatureVersion=1.0&Timestamp=2022-09-19T12%3A06%3A41Z&Version=2017-03-21&VideoId=bca6bd1d1b83454f840cfb7fa1de5ca6&Signature=Lv4cpbyBH7T*********%3D",
  "name": "MissingChannelError",
  "data": {},
  "code": "MissingChannel",
  "url": "http://vod.cn-shanghai.aliyuncs.com/?AccessKeyId=LTAI5t8QW*********&Action=GetVideoPlayInfo&Format=JSON&SignatureMethod=HMAC-SHA1&SignatureNonce=04c47f8fd9f62f*********&SignatureVersion=1.0&Timestamp=2022-09-19T12%3A06%3A41Z&Version=2017-03-21&VideoId=bca6bd1d1b83454f840cfb7fa1de5ca6&Signature=Lv4cpbyBH7Tq*********",
  "entry": {
    "url": "http://vod.cn-shanghai.aliyuncs.com/?AccessKeyId=LTAI5t8QW*********&Action=GetVideoPlayInfo&Format=JSON&SignatureMethod=HMAC-SHA1&SignatureNonce=04c47f8fd9f62f1*********&SignatureVersion=1.0&Timestamp=2022-09-19T12%3A06%3A41Z&Version=2017-03-21&VideoId=bca6bd1d1b83454f840cfb7fa1de5ca6&Signature=Lv4cpbyBH7TqS*********%3D"
  }
}


```

附上SDK调用代码片段：
```
const resp: any = await client.request('GetVideoPlayInfo',
  {
    VideoId: videoId
  })
```

**Comment by mr-xiangxu** [comment]
API名字错写成了GetVideoPlayInfo，应该是GetPlayInfo
